BEGIN;

DROP TABLE IF EXISTS
"variation_detail",
"detail_variation_service",
"service",
"variation_service",
"service_question",
"question",
"service_advantage", 
"advantage",
"project",
"project_image",
"technology_project",
"technology";

CREATE TABLE "service" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "icon"  text NOT NULL,
    "name" text NOT NULL,
    "slug" text NOT NULL,
    "card_description" text NOT NULL,
    "image" text NOT NULL,
    "short_description" text NOT NULL,
    "long_description" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "variation_service" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" text NOT NULL,
    "wordpress_price" text,
    "development_price" text,
    "service_id" integer NOT NULL REFERENCES "service"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "detail_variation_service" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "variation_detail" (
    "variation_id" integer NOT NULL REFERENCES "variation_service"("id"),
    "detail_id" integer NOT NULL REFERENCES "detail_variation_service"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz,
    PRIMARY KEY ("variation_id", "detail_id")
);


CREATE TABLE "question" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "question"  text NOT NULL,
    "answer"  text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "service_question" (
    "service_id" integer NOT NULL REFERENCES "service"("id"),
    "question_id" integer NOT NULL REFERENCES "question"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz,
     PRIMARY KEY ("service_id", "question_id")
);

CREATE TABLE "advantage" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name"  text NOT NULL,
    "description"  text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "service_advantage" (
    "service_id" integer NOT NULL REFERENCES "service"("id"),
    "advantage_id" integer NOT NULL REFERENCES "advantage"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz,
     PRIMARY KEY ("service_id", "advantage_id")
);

CREATE TABLE "project" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "image"  text NOT NULL,
    "name" text NOT NULL,
    "slug" text NOT NULL,
    "card_description" text NOT NULL,
    "short_description" text NOT NULL,
    "long_description" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "project_image" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "image" text NOT NULL,
    "project_id" integer NOT NULL REFERENCES "project"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "technology" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "icon"  text NOT NULL,
    "name"  text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "technology_project" (
    "project_id" integer NOT NULL REFERENCES "project"("id"),
    "technology_id" integer NOT NULL REFERENCES "technology"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz,
    PRIMARY KEY ("project_id", "technology_id")
);

COMMIT;
